homework_4 done
eugene-okulik/mikhail.luzan pull request #3
Opened 2024-03-15 08:00 UTC by M4e5tRO

Mikhail Luzan: homework_4 completed

2024-03-15 09:17 UTC, eugene-okulik requested changes

2024-03-15 09:17 UTC, eugene-okulik commented on homework/mikhail_luzan/Homework_4/hw_4.py
> +my_dict['dict']['i am a tuple'] = (1, 2, 3)
В задании было 

> добавьте элемент с ключом ('i am a tuple',) и любым значением

Ты выполнил так, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Содержимое этого ключа намекает на то, чем он должен быть

2024-03-15 12:01 UTC, eugene-okulik requested changes

2024-03-15 12:01 UTC, eugene-okulik commented on homework/mikhail_luzan/Homework_4/hw_4.py
> +my_dict['dict']['dict_tuple'] = ('i am a tuple', 'element 2', 'element 3')
Ты изменил значение - оно по заданию может быть любым. `('i am a tuple',)` должно быть ключом.

2024-03-15 13:10 UTC, M4e5tRO commented on homework/mikhail_luzan/Homework_4/hw_4.py
> +my_dict['dict']['dict_tuple'] = ('i am a tuple', 'element 2', 'element 3')
Женя, сорри, что не понял задания.
Ключ `('i am a tuple' ,)` немного смущает, вернее запятая в нем.

Такой вариант будет верным? :  `my_dict['dict'][('i am a tuple', )] = ('element 1', )`

2024-03-15 14:33 UTC, eugene-okulik commented on homework/mikhail_luzan/Homework_4/hw_4.py
> +my_dict['dict']['dict_tuple'] = ('i am a tuple', 'element 2', 'element 3')
Ага. Это задание я сделал специально, чтобы еще раз обратить внимание на две вещи:
1. Ключом словаря может быть кортеж
2. Кортеж с одним значением выглядит вот так

2024-03-16 11:26 UTC, eugene-okulik approved these changes

2024-03-16 11:26 UTC, merged