homework_6 done
eugene-okulik/mikhail.luzan pull request #5
Opened 2024-04-03 07:54 UTC by M4e5tRO

Mikhail Luzan: homework_6 completed

2024-04-03 08:02 UTC, M4e5tRO commented
@eugene-okulik вопрос по ошибке линтера - ./homework/mikhail_luzan/Homework_6/task_1.py:2:119: W504 line break after binary operator

По видео из первого урока, мы говорили про добавление знака '+' при переносе текста для лучшей читабельности.
А здесь линтер считает это ошибкой?

2024-04-04 08:42 UTC, eugene-okulik commented
> @eugene-okulik вопрос по ошибке линтера - ./homework/mikhail_luzan/Homework_6/task_1.py:2:119: W504 line break after binary operator
> 
> По видео из первого урока, мы говорили про добавление знака '+' при переносе текста для лучшей читабельности. А здесь линтер считает это ошибкой?

Долгое время плюсик после первой строки или перед второй строкой считались одинаково хорошими и шел разговор о том, чтобы признать один из подходов не рекомендуемым. И сейчас, вижу, таки решили это сделать. Поэтому правильным вариантом считается плюс перед первой строкой.

2024-04-04 08:46 UTC, eugene-okulik requested changes
Подправь все, на что ругается линт и пойдем дальше

2024-04-04 08:46 UTC, eugene-okulik commented on homework/mikhail_luzan/Homework_6/task_1.py
> +        ' dignissim vitae libero'
Ну и еще линту не нравится, что у тебя здесь отступ не 4 пробела.

2024-04-05 10:05 UTC, eugene-okulik approved these changes

2024-04-05 10:05 UTC, merged